version: 2.1

orbs:
  # orb info: https://circleci.com/developer/orbs/orb/rynkowsg/checkout
  checkout: rynkowsg/checkout@0.2.0
  # orb info: https://circleci.com/developer/orbs/orb/rynkowsg/mise
  # changelog: https://github.com/rynkowsg/mise-orb/blob/main/CHANGELOG.md
  mise: rynkowsg/mise@0.1.0
  # orb info: https://circleci.com/developer/orbs/orb/rynkowsg/rynkowsg
  rynkowsg: rynkowsg/rynkowsg@0.4.0

jobs:
  test:
    executor: rynkowsg/docker_x86_cimg_base
    steps:
      - checkout/checkout: {depth: 1}
      - mise/setup:
          mise_version: v2026.9.4 # https://github.com/jdx/mise/releases
          # java is here because babashka needs it.
          tools: >-
            babashka java
            bats
            shellcheck
            shfmt
      - run: bb lint
      - run: bb format check
      - run: bb test

workflows:
  main:
    jobs:
      - test
